theme: jekyll-theme-cayman
name: PnT SDK Guide
description: PnT SDK Guide
markdown: kramdown

# The font used for headings. Expects a string that is a valid CSS font-family value.
font_heading: "'Roboto Slab', 'Nanum Gothic', Helvetica, Arial, sans-serif"

# The text font. Expects a string that is a valid CSS font-family value.
font: "'Noto Sans', 'Nanum Gothic', Helvetica, Arial, sans-serif"

# The string encoding what fonts to fetch from Google Fonts.
# See: https://qwtel.com/hydejack/docs/configuration/
google_fonts: Roboto+Slab:700|Noto+Sans:400,400i,700,700i

# If you do not use a Google Fonts, uncomment the line below
# no_google_fonts: true
